ver: 2 # config 版本

service: # 訂閱的服務
  - trem.rts
  - trem.eew
  - trem.intensity
  - websocket.eew
  - websocket.report
  - cwa.intensity

server: # websocket 伺服器地址
  - lb-1.exptech.dev
  - lb-2.exptech.dev
  - lb-3.exptech.dev
  - lb-4.exptech.dev

SHOW_BOTH_EEW: false